### ISSUE TITLE
Not Supported on iPhone6

### ISSUE THREAD

**Issue by idanasher** [DigitalStrawberry/ANE-DeferSystemGestures#1]
I  get : 
DeferSystemGestures.instance.isSupported == false
using a very simple test project
with iPhone6 - ios 11.2.6
AIR 28.0.0.120
Animate CC 2018

this is the code:
_### import com.digitalstrawberry.ane.system.*;

trace(" here 1 ");
trace(" here 2 " + DeferSystemGestures.instance.isSupported);
if(DeferSystemGestures.instance.isSupported)
{
    trace("3");
	DeferSystemGestures.instance.setScreenEdges(ScreenEdges.TOP | ScreenEdges.BOTTOM);
}_

**Comment by idanasher** [comment]
SORRY, ALL IS WORKING !

when i have downloaded and used the latest  .ane & .swc files (and not the source code)
It is working GREAT!

Marpies you are a GREAT MAN 
You saved me a LOT !! 

btw, how is that we don't see a lot of complaints regrading this issue ?
I have wasted couple of days on it, and I find it very strange that there is not any forum-info-related on this issue. 
I find  a great & critical necessity in this behavior for ios developers. 

and another thing, what will happen on iPhone with  ios 10 ?

**Comment by marpies** [comment]
Glad you got it working! I agree the new behavior is quite annoying. I think the issue affects iOS 11 only so the system arrow should show up on devices running iOS 10.
